### ISSUE TITLE
Plugin not working anymore

### ISSUE THREAD

**Issue by tischi** [embl-cba/fiji-plugin-cats#13]
@davodogster

```
Caused by: java.lang.NoSuchFieldError: offset
                at de.embl.cba.cats.utils.IntervalUtils.convertIntervalToRegion5D(IntervalUtils.java:137)
                at de.embl.cba.cats.features.FeatureProvider.createDataCubeIncludingOutOfBoundsPixels(FeatureProvider.java:1229)
                at de.embl.cba.cats.features.FeatureProvider.getDataCube(FeatureProvider.java:1197)
                at de.embl.cba.cats.features.FeatureProvider.getProcessedOriginalImage(FeatureProvider.java:1625)
                at de.embl.cba.cats.features.FeatureProvider.computeFeatureImages(FeatureProvider.java:1332)
                at de.embl.cba.cats.features.FeatureProvider.computeFeatures(FeatureProvider.java:1145)
                at de.embl.cba.cats.CATS.configureFeatureProvider(CATS.java:2993)
                at de.embl.cba.cats.CATS.lambda$applyClassifier$1(CATS.java:2905)
                at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
                ... 4 more
```

**Comment by tischi** [comment]
I looked into this.
The error comes from a method in another plugin: `plugins/fiji_plugin_bigDataProcessor` 
Somehow this was out of date on your Fiji. I do not really understand why.
Anyway, can you update your Fiji and try again? 
**You are getting CATS updating via update site `EMBL-CBA`, right?**
If there still is an error I would need you to go into the plugins folder and tell me the version of above plugin (it is in the filename).

**Comment by davodogster** [comment]
**Just updated again today:**
fiji_plugin_bigDataProcessor-0.6.00.jar

![image](https://user-images.githubusercontent.com/46079516/59016759-1a58a600-8896-11e9-84e2-1951021c9645.png)

**When trying to train in CATS:**

[INFO] Allocated memory for result image.
[INFO] Computing features values for 14 label groups using 12 threads.
[INFO] Label set 1/14: Computing features for 1 label(s)...
[INFO] Label set 3/14: Computing features for 1 label(s)...
[INFO] Label set 2/14: Computing features for 1 label(s)...
[INFO] Label set 4/14: Computing features for 1 label(s)...
[INFO] Label set 6/14: Computing features for 1 label(s)...
java.util.concurrent.ExecutionException: java.lang.NoSuchFieldError: offset[INFO] Label set 5/14: Computing features for 1 label(s)...
[INFO] Label set 8/14: Computing features for 1 label(s)...

[INFO] Label set 7/14: Computing features for 1 label(s)...
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
[INFO] Label set 10/14: Computing features for 1 label(s)...
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)[INFO] Label set 9/14: Computing features for 1 label(s)...

	at de.embl.cba.cats.utils.ThreadUtils.joinThreads(ThreadUtils.java:48)[INFO] Label set 12/14: Computing features for 1 label(s)...

	at de.embl.cba.cats.CATS.updateInstancesValuesOfGroupedLabels(CATS.java:1790)[INFO] Label set 11/14: Computing features for 1 label(s)...

	at de.embl.cba.cats.CATS.computeUpdatedLabelsInstances(CATS.java:1768)[INFO] Label set 14/14: Computing features for 1 label(s)...

[INFO] Label set 13/14: Computing features for 1 label(s)...
	at de.embl.cba.cats.CATS.updateLabelInstancesAndMetadata(CATS.java:1728)
	at de.embl.cba.cats.CATS.updateLabelInstancesAndMetadata(CATS.java:1711)
	at de.embl.cba.cats.CATS.updateLabelInstances(CATS.java:1193)
	at de.embl.cba.cats.ui.CATSCommand.updateLabelInstances(CATSCommand.java:432)
	at de.embl.cba.cats.ui.CATSCommand.lambda$updateLabelsAndTrainClassifier$2(CATSCommand.java:541)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NoSuchFieldError: offset
	at de.embl.cba.cats.utils.IntervalUtils.convertIntervalToRegion5D(IntervalUtils.java:137)
	at de.embl.cba.cats.features.FeatureProvider.createWithinBoundsDataCube(FeatureProvider.java:1296)
	at de.embl.cba.cats.features.FeatureProvider.getDataCube(FeatureProvider.java:1193)
	at de.embl.cba.cats.features.FeatureProvider.getProcessedOriginalImage(FeatureProvider.java:1625)
	at de.embl.cba.cats.features.FeatureProvider.computeFeatureImages(FeatureProvider.java:1332)
	at de.embl.cba.cats.features.FeatureProvider.computeFeatures(FeatureProvider.java:1145)
	at de.embl.cba.cats.CATS.lambda$computeLabelsInstanceValues$0(CATS.java:1946)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	... 1 more
[INFO] Computed feature values for 14 labels; total number of labels is 14
Exception in thread "Thread-37" java.lang.NullPointerException
	at de.embl.cba.cats.instances.InstancesUtils.getInstancesHeader(InstancesUtils.java:625)
	at de.embl.cba.cats.instances.InstancesUtils.createInstancesAndMetadataFromLabels(InstancesUtils.java:47)
	at de.embl.cba.cats.CATS.putLabelsIntoInstancesAndMetadata(CATS.java:1737)
	at de.embl.cba.cats.CATS.updateLabelInstancesAndMetadata(CATS.java:1729)
	at de.embl.cba.cats.CATS.updateLabelInstancesAndMetadata(CATS.java:1711)
	at de.embl.cba.cats.CATS.updateLabelInstances(CATS.java:1193)
	at de.embl.cba.cats.ui.CATSCommand.updateLabelInstances(CATSCommand.java:432)
	at de.embl.cba.cats.ui.CATSCommand.lambda$updateLabelsAndTrainClassifier$2(CATSCommand.java:541)
	at java.lang.Thread.run(Thread.java:748)

**Comment by davodogster** [comment]
Hi Christian.

I followed your update advice and CATS (updated FIJI for the second time today) appears to be working as normal as I just trained a new classifier and applied it to a full image in the GUI.

![image](https://user-images.githubusercontent.com/46079516/59017300-50e2f080-8897-11e9-8b42-466d9d883e55.png)


Thanks a lot! Sam

**Comment by tischi** [comment]
👍
