### ISSUE TITLE
cannot add a new label right now

### ISSUE THREAD

**Issue by davodogster** [embl-cba/fiji-plugin-cats#15]
I received a random error I don’t even think I clicked apply classifier.

[INFO]

Apply classifier

[INFO] # Generating tiles for interval:
[INFO] Interval:
Exception in thread “Thread-3156” java.lang.NullPointerException
at de.embl.cba.cats.utils.IntervalUtils.logInterval(IntervalUtils.java:65)
at de.embl.cba.cats.utils.IntervalUtils.createTiles(IntervalUtils.java:159)
at de.embl.cba.cats.CATS.applyClassifierWithTiling(CATS.java:2683)
at de.embl.cba.cats.CATS.applyClassifierWithTiling(CATS.java:2559)
at de.embl.cba.cats.ui.CATSCommand.lambda$applyClassifier$1(CATSCommand.java:397)
at java.lang.Thread.run(Thread.java:748)
[ERROR] Sorry, but I am busy and cannot add a new label right now…
[ERROR] Sorry, but I am busy and cannot add a new label right now…
[ERROR] Sorry, but I am busy and cannot add a new label right now…
[ERROR] Sorry, but I am busy and cannot add a new label right now…
[ERROR] Sorry, but I am busy and cannot add a new label right now…
[ERROR] Sorry, but I am busy and cannot add a new label right now…

**Comment by tischi** [comment]
1. You cannot add new labels while classification is in progress.
1. I think however that in your case it falsely thought it was in classification mode. The reason was that it could not retrieve the classification region (for some reason) but still entered the classification mode, where it then crashed. I tried to change the code such that this cannot happen anymore. If your update your Fiji you will have those changes. I hope it helps.

**Comment by tischi** [comment]
Hi Sam,

Did that happen again? Otherwise I would close this issue.
