### ISSUE TITLE
Lost all labels of one class

### ISSUE THREAD

**Issue by davodogster** [embl-cba/fiji-plugin-cats#18]
I noticed that all the ROIS dissipated for one class and were not in the ROI manager when reviewing and I received a random Error when reviewing the labels:

Exception in thread "Thread-2075" java.lang.NullPointerException
	at ij.plugin.frame.RoiManager.add(RoiManager.java:470)
	at de.embl.cba.cats.ui.Overlays.addRoiToRoiManager(Overlays.java:348)
	at de.embl.cba.cats.ui.Overlays.addRoisToRoiManager(Overlays.java:342)
	at de.embl.cba.cats.ui.Overlays.reviewLabelsInRoiManager(Overlays.java:329)
	at de.embl.cba.cats.ui.Overlays.reviewLabelsInRoiManagerUI(Overlays.java:295)
	at de.embl.cba.cats.ui.CATSCommand.lambda$executeAction$0(CATSCommand.java:241)
	at java.lang.Thread.run(Thread.java:748) 

Training:
[INFO] Computing features values for 6 label groups using 12 threads.
[INFO] Label set 1/6: Computing features for 1 label(s)...
[INFO] Label set 2/6: Computing features for 1 label(s)...
[INFO] Label set 3/6: Computing features for 1 label(s)...
[INFO] Label set 3/6: ...done
[INFO] Label set 2/6: ...done
[INFO] Label set 5/6: Computing features for 1 label(s)...
[INFO] Label set 4/6: Computing features for 1 label(s)...
[INFO] Label set 1/6: ...done
[INFO] Label set 6/6: Computing features for 1 label(s)...
[INFO] Label set 6/6: ...done
[INFO] Label set 5/6: ...done
[INFO] Label set 4/6: ...done
[INFO] Computed feature values for 6 labels; total number of labels is 318
[INFO] 
# Instances information
[INFO] Number of instances: 4941
[INFO] Number of attributes: 613
Exception in thread "Thread-2088" java.lang.ArrayIndexOutOfBoundsException: 1
	at de.embl.cba.cats.labels.LabelManager.getNumLabelsPerClass(LabelManager.java:113)
	at de.embl.cba.cats.ui.LabelButtonsPanel.setLabellingInformations(LabelButtonsPanel.java:77)
	at de.embl.cba.cats.ui.CATSCommand.updateLabelInstances(CATSCommand.java:434)
	at de.embl.cba.cats.ui.CATSCommand.lambda$updateLabelsAndTrainClassifier$2(CATSCommand.java:541)
	at java.lang.Thread.run(Thread.java:748)

**Comment by tischi** [comment]
Thanks for reporting!
Did it happen again?
I will try to see whether I can understand what could have happened....
