### ISSUE TITLE
Feature Computation Slow

### ISSUE THREAD

**Issue by davodogster** [embl-cba/fiji-plugin-cats#7]
Computing the Features is very slow (using 12 cores/threads and 30GB RAM), and at any given time it appears that 4 or 5 of the cores are doing work. Using variable sized ROI's (polygons/lines) in an 8000 x 12000 pixel image.

**Comment by davodogster** [comment]
It's set at 49GB and 12 threads. CATS tells me that 12 threads are being used (3 per channel I think), but when I check the task manager, more than half of the cores are doing minimal work.

**Comment by tischi** [comment]
Thanks! This is very interesting. I will look into this today!

**Comment by tischi** [comment]
General question: Are you having 2D or 3D data for this example?

**Comment by davodogster** [comment]
2D

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by tischi** [comment]
I added an option to the user interface to change the memory and threads. 
Could you please play with this and see whether it improves the performance?
The idea would be that you "over-commit", i.e. put higher values (for both memory and threads) than your computer really has and explore what happens.
<img width="661" alt="image" src="https://user-images.githubusercontent.com/2157566/57511210-09555d00-7309-11e9-9f14-f508a43275aa.png">

**Comment by davodogster** [comment]
A couple of examples here - Results not displaying in GUI, and inefficient/slow classification.


per tree: 7469.22
[INFO] FastRandomForest of 50 trees, each constructed while considering 62 random features.
Out of bag error: 8.78325%

[INFO] Trained classifier in 2360 ms.
[INFO] 
# Apply classifier
[INFO] # Generating tiles for interval:
[INFO] Interval: 
[INFO] x: 0, 4692
[INFO] y: 0, 4009
[INFO] z: 0, 0
[INFO] t: 0, 0
[INFO] Tile sizes [x,y,z]: 1565, 1337, 1
[INFO] Number of tiles: 9
[INFO] Tile threads: 3
[INFO] Threads per tile: 3
[INFO] Image features at level 0 computed in [ms]: 1266, using 3 threads.
[INFO] Image features at level 0 computed in [ms]: 1266, using 3 threads.
[INFO] Image features at level 0 computed in [ms]: 1875, using 3 threads.
[INFO] Image features at level 1 computed in [ms]: 1156, using 3 threads.
[INFO] Image features at level 1 computed in [ms]: 1687, using 3 threads.
[INFO] Image features at level 2 computed in [ms]: 641, using 3 threads.
[INFO] Image features at level 2 computed in [ms]: 1140, using 3 threads.
[INFO] Image features at level 1 computed in [ms]: 2125, using 3 threads.
[INFO] Image features at level 3 computed in [ms]: 1391, using 3 threads.
[INFO] Image features at level 2 computed in [ms]: 875, using 3 threads.
[INFO] Image features at level 3 computed in [ms]: 1610, using 3 threads.
[INFO] Image features at level 3 computed in [ms]: 969, using 3 threads.
[INFO] Image features at level 0 computed in [ms]: 1343, using 3 threads.
[INFO] Image features at level 0 computed in [ms]: 1594, using 3 threads.
[INFO] Image features at level 0 computed in [ms]: 1625, using 3 threads.
[INFO] Image features at level 1 computed in [ms]: 1282, using 3 threads.
[INFO] Image features at level 1 computed in [ms]: 1500, using 3 threads.
[INFO] Image features at level 2 computed in [ms]: 1093, using 3 threads.
[INFO] Image features at level 2 computed in [ms]: 859, using 3 threads.
[INFO] Image features at level 1 computed in [ms]: 1906, using 3 threads.
[INFO] Image features at level 3 computed in [ms]: 1125, using 3 threads.
[INFO] Image features at level 3 computed in [ms]: 1391, using 3 threads.
[INFO] Image features at level 2 computed in [ms]: 1360, using 3 threads.
[INFO] Image features at level 3 computed in [ms]: 984, using 3 threads.
[INFO] Image features at level 0 computed in [ms]: 1625, using 3 threads.
[INFO] Image features at level 0 computed in [ms]: 1890, using 3 threads.
[INFO] Image features at level 0 computed in [ms]: 1625, using 3 threads.
[INFO] Image features at level 1 computed in [ms]: 1515, using 3 threads.
[INFO] Image features at level 1 computed in [ms]: 1500, using 3 threads.
[INFO] Image features at level 2 computed in [ms]: 906, using 3 threads.
[INFO] Image features at level 2 computed in [ms]: 891, using 3 threads.
[INFO] Image features at level 1 computed in [ms]: 2375, using 3 threads.
[INFO] Image features at level 3 computed in [ms]: 1251, using 3 threads.
[INFO] Anisotropy setting: 1.0
[INFO] Number of active features: 146
[INFO] Features computed in [ms]: 16750, using 3 threads
[INFO] Classifying pixels...
[INFO] Image features at level 3 computed in [ms]: 2406, using 3 threads.
[INFO] Anisotropy setting: 1.0
[INFO] Number of active features: 146
[INFO] Features computed in [ms]: 18140, using 3 threads
[INFO] Classifying pixels...
[INFO] Image features at level 2 computed in [ms]: 2594, using 3 threads.
[INFO] Image features at level 3 computed in [ms]: 3236, using 3 threads.
[INFO] Anisotropy setting: 1.0
[INFO] Number of active features: 146
[INFO] Features computed in [ms]: 22329, using 3 threads
[INFO] Classifying pixels...
[INFO] [PROGRESS]: Classification Tile: 1/9; Time (spent, left) [min]: 1.3, 10.3 (81 kv/s); Trees (avg, max, avail): 12, 50, 50; Memory (current, max, avail) [MB]: 3022, 3022, 25699; 
[INFO] [PROGRESS]: Classification Tile: 2/9; Time (spent, left) [min]: 1.3, 4.5 (80 kv/s); Trees (avg, max, avail): 12, 50, 50; Memory (current, max, avail) [MB]: 452, 452, 25699; 
[INFO] [PROGRESS]: Classification Tile: 3/9; Time (spent, left) [min]: 1.3, 2.6 (80 kv/s); Trees (avg, max, avail): 12, 50, 50; Memory (current, max, avail) [MB]: 460, 460, 25699; 
[INFO] [PROGRESS]: Classification Tile: 4/9; Time (spent, left) [min]: 2.5, 3.1 (69 kv/s); Trees (avg, max, avail): 12, 50, 50; Memory (current, max, avail) [MB]: 8386, 8386, 25699; 
[INFO] [PROGRESS]: Classification Tile: 5/9; Time (spent, left) [min]: 3.1, 2.5 (65 kv/s); Trees (avg, max, avail): 12, 50, 50; Memory (current, max, avail) [MB]: 8641, 8641, 25699; 
[INFO] [PROGRESS]: Classification Tile: 6/9; Time (spent, left) [min]: 3.7, 1.9 (56 kv/s); Trees (avg, max, avail): 12, 50, 50; Memory (current, max, avail) [MB]: 5770, 5770, 25699; 
[INFO] [PROGRESS]: Classification Tile: 7/9; Time (spent, left) [min]: 4.9, 1.4 (50 kv/s); Trees (avg, max, avail): 12, 50, 50; Memory (current, max, avail) [MB]: 8451, 8451, 25699; 
[INFO] [PROGRESS]: Classification Tile: 8/9; Time (spent, left) [min]: 5.2, 0.6 (57 kv/s); Trees (avg, max, avail): 14, 50, 50; Memory (current, max, avail) [MB]: 5716, 5716, 25699; 
[INFO] [PROGRESS]: Classification Tile: 9/9; Time (spent, left) [min]: 5.3, 0.0 (59 kv/s); Trees (avg, max, avail): 16, 50, 50; Memory (current, max, avail) [MB]: 2879, 2879, 25699; 
[INFO] Exporting results, using modality: Show in ImageJ
[INFO] 
Computing probability image, using 8 threads.
Exception in thread "Thread-184" java.lang.IllegalArgumentException: Argument out of range: 2[INFO] Creating binned class image;  0/1; Time (spent, to-go, per task) [min]: 0.0, Infinity, Infinity; Memory (current, avail) [MB]: 355, 25699; 

	at ij.ImageStack.setSliceLabel(ImageStack.java:259)
	at de.embl.cba.cats.results.ResultExport.setSliceLabels(ResultExport.java:348)
	at de.embl.cba.cats.results.ResultExport.createImagePlusForClass(ResultExport.java:273)
	at de.embl.cba.cats.results.ResultExport.exportClasses(ResultExport.java:439)
	at de.embl.cba.cats.results.ResultExport.exportResults(ResultExport.java:322)
	at de.embl.cba.cats.results.ResultImageRAM.exportResults(ResultImageRAM.java:60)
	at de.embl.cba.cats.results.ResultImageExportGUI.showExportGUI(ResultImageExportGUI.java:65)
	at de.embl.cba.cats.ui.CATSCommand.lambda$executeAction$0(CATSCommand.java:292)
	at java.lang.Thread.run(Thread.java:748)

**Comment by tischi** [comment]
@metavibor @davodogster 
Could you guys post a screenshot here of your data? So much zoomed in that one can see the pixels?
I am asking, because if at the highest zoom there is not much information one can change the feature settings of CATS in a way that it might be much faster, i.e. ignoring the full resolution and only start computing features at a, say, 3x3 binning...

**Comment by tischi** [comment]
> Computing probability image, using 8 threads.
Exception in thread "Thread-184" java.lang.IllegalArgumentException: Argument out of range: 2[INFO] Creating binned class image; 0/1; Time (spent, to-go, per task) [min]: 0.0, Infinity, Infinity; Memory (current, avail) [MB]: 355, 25699;

This is strange. Could you send me the image and the .ARFF file? Then I can try to reproduce it and fix it.

**Comment by tischi** [comment]
Did it help to over-commit the memory or threads?
